language: generic
sudo: required
services:
  - docker





before_install:
  - docker build -t neerajnsharma/docker-react -f Dockerfile .


script:
  - docker run neerajnsharma/docker-react npm run test -- --coverage


deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-954603344051"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 
